#!/usr/bin/env python3
"""Build the work's ledger (nights.json) from the committed material — nothing else.

Two Nights Deep, works/two-nights-deep/ (form fixed night 12, FORM.md §3: the
ledger is regenerated by this committed script, never hand-edited). Inputs are
the committed evidence of the continuing look; when a later session's look adds
a newer join or rewrite record, it extends SOURCES by dated revision and
re-runs this script. Attribution for all sky values: Source: Deutscher
Wetterdienst (DWD), Climate Data Center, hourly cloud cover, station 00433
Berlin-Tempelhof, CC BY 4.0.

Run from this directory: python3 build.py   (writes nights.json beside itself)
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

SOURCES = {
    # the newest committed join: every recorded wake x the sky's record
    "join": "material/night-sky/2026-08-25-continuing/join.json",
    # every committed record of the archive re-saying an already-written hour,
    # oldest first; each names the readings its two states belong to
    "rewrites": [
        {
            "path": "material/night-sky/2026-08-24-continuing/indicator-rewrite-2026-08-20.txt",
            "first_read": "2026-08-22",
            "retold_read": "2026-08-24",
        },
        {
            # rows before 2026-08-22 00:00 were first committed in the prospect
            # slice (read 2026-08-22); the 2026-08-22 00:00 row in the
            # eighth-date slice (read 2026-08-24) — per the file's own header
            "path": "material/night-sky/2026-08-25-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"before 2026082200": "2026-08-22", "2026082200": "2026-08-24"},
            "retold_read": "2026-08-25",
        },
    ],
    # the practice's dated readings of the archive, with where the boundary
    # between instrument-told and person-told rows stood in each (the frontier;
    # material/night-sky/2026-08-25-continuing/README.md, finding 1)
    "readings": [
        {"read": "2026-08-22", "generation": "2026-08-22 08:18",
         "person_rows_begin": "2026-08-20 01:00 UTC",
         "evidence": "material/night-sky/2026-08-22-prospect/"},
        {"read": "2026-08-24", "generation": "2026-08-23 08:18",
         "person_rows_begin": "2026-08-21 01:00 UTC",
         "evidence": "material/night-sky/2026-08-24-continuing/"},
        {"read": "2026-08-25", "generation": "2026-08-24 08:18",
         "person_rows_begin": "2026-08-22 01:00 UTC",
         "evidence": "material/night-sky/2026-08-25-continuing/"},
    ],
}

# hours the archive has re-said, from the committed rewrite records:
# MESS_DATUM -> {first, current, first_read, retold_read}
retold = {}
row_re = re.compile(r"^(\d{10})\s")
for rw in SOURCES["rewrites"]:
    for line in open(os.path.join(ROOT, rw["path"])):
        m = row_re.match(line)
        if not m:
            continue
        key = m.group(1)
        # both file forms carry the two indicator states as ';P;' -> ';I;' etc.
        states = re.findall(r";\s*(P|I|-999)\s*;", line)
        if len(states) >= 2:
            fr = rw["first_read"]
            if isinstance(fr, dict):
                fr = fr.get(key) or fr["before 2026082200"]
            retold[key] = {
                "first": states[0], "current": states[-1],
                "first_read": fr, "retold_read": rw["retold_read"],
                "evidence": rw["path"],
            }

join = json.load(open(os.path.join(ROOT, SOURCES["join"])))
wakes = []
for r in join:
    key = r["wake_utc"][:13].replace("-", "").replace("T", "")
    entry = {
        "session": r["session"],
        "record": r["record"],
        "wake_utc": r["wake_utc"],
        "berlin_local": r["berlin_local_cest"],
        "sky_eighths": r["cloud_cover_eighths_wake_hour"],
        "indicator": r["measurement_indicator"],
    }
    if key in retold:
        entry["retold"] = retold[key]
    wakes.append(entry)

ledger = {
    "work": "two-nights-deep",
    "note": ("The work's ledger, derived from the committed record alone by "
             "build.py (FORM.md §3). One entry per recorded wake of the "
             "practice's life; sky values as the archive first told them in "
             "the practice's committed slices; 'retold' where the archive's "
             "later generations re-said the hour. sky_eighths null = the "
             "world had not written that night as of the build."),
    "attribution": ("Source: Deutscher Wetterdienst (DWD), Climate Data "
                    "Center, hourly cloud cover (V_N, eighths), station "
                    "00433 Berlin-Tempelhof, CC BY 4.0"),
    "sources": SOURCES,
    "wakes": wakes,
}
json.dump(ledger, open(os.path.join(HERE, "nights.json"), "w"), indent=1)
unwritten = [w for w in wakes if w["sky_eighths"] is None]
print(f"{len(wakes)} wakes; {len(unwritten)} unwritten "
      f"({[w['session'] for w in unwritten]}); {len(retold)} hours retold, "
      f"{sum(1 for w in wakes if 'retold' in w)} of them at a wake hour")
