#!/usr/bin/env python3
"""Build the work's ledger (nights.json) from the committed material — nothing else.

Two Nights Deep, works/two-nights-deep/ (form fixed night 12, FORM.md §3: the
ledger is regenerated by this committed script, never hand-edited). Inputs are
the committed evidence of the continuing look; when a later session's look adds
a newer join or rewrite record, it extends SOURCES by dated revision and
re-runs this script. Attribution for all sky values: Source: Deutscher
Wetterdienst (DWD), Climate Data Center, hourly cloud cover, station 00433
Berlin-Tempelhof, CC BY 4.0.

Run from this directory: python3 build.py   (writes nights.json beside itself)

Revisions:
- night 12 (record 37, 2026-08-25): first form.
- night 13 (record 38, 2026-08-28): SOURCES advanced to the fourth act's join
  and its rewrite frontier; the first_read of a rewrite record generalized from
  a single hardcoded boundary to a threshold form (see resolve_first_read), so a
  frontier file that spans two first-telling dates resolves each row correctly.
  Night 12's frontier entry restated in the same threshold form (identical
  result). No output field changed shape.
- night 15 (record 40, 2026-08-29): SOURCES advanced to the fifth act's join
  (nights 14 and 15 enter as wakes; night 13's hour written 8/8) and its rewrite
  frontier (24 rows, all first committed 2026-08-28 — a plain first_read); the
  fifth dated reading appended. No logic changed.
- night 16 (record 41, 2026-08-30): SOURCES advanced to the sixth act's join
  (night 16 enters as a wake; night 14's hour written 8/8) and its rewrite
  frontier (24 rows spanning two first-committed dates — threshold form:
  2026-08-26 rows first committed 2026-08-28, the 2026-08-27 00:00 row
  2026-08-29); the sixth dated reading appended. No logic changed.
- night 17 (record 42, 2026-08-31): SOURCES advanced to the seventh act's join
  (night 17 enters as a wake; night 15's hour written 8/8) and its rewrite
  frontier (24 rows spanning two first-committed dates — threshold form:
  2026-08-27 rows first committed 2026-08-29, the 2026-08-28 00:00 row
  2026-08-30; night 13's wake hour among them); the seventh dated reading
  appended. No logic changed.
- night 18 (record 43, 2026-09-01): SOURCES advanced to the eighth act's join
  (night 18 enters as a wake; night 16's hour written 8/8) and its rewrite
  frontier (24 rows spanning two first-committed dates — threshold form:
  2026-08-28 rows first committed 2026-08-30, the 2026-08-29 00:00 row
  2026-08-31; night 14's wake hour among them); the eighth dated reading
  appended. No logic changed.
- night 19 (record 44, 2026-09-02): SOURCES advanced to the ninth act's join
  (night 19 enters as a wake; night 17's hour written 7/8) and its rewrite
  frontier (24 rows spanning two first-committed dates — threshold form:
  2026-08-29 rows first committed 2026-08-31, the 2026-08-30 00:00 row
  2026-09-01; night 15's wake hour among them); the ninth dated reading
  appended. No logic changed.
- night 20 (record 45, 2026-09-03): SOURCES advanced to the tenth act's join
  (night 20 enters as a wake; nights 18 AND 19's hours written in one reading —
  8/8 and 0/8, the first single entering civil date to carry two wake hours;
  night 13's reading had delivered two across two entering dates — leaving only
  tonight unwritten) and its rewrite frontier (24 rows spanning two
  first-committed dates — threshold form: 2026-08-30 rows first committed
  2026-09-01, the 2026-08-31 00:00 row 2026-09-02; night 16's wake hour among
  them); the tenth dated reading appended. One shape change, for the page's
  readings figure (FORM.md §5, added tonight): every reading entry now carries
  "window_end" — the last hour the archive's window held at that reading,
  verbatim from the committed fetch transcripts ("last data row"; for the first
  reading, the prospect slice's span end as stated in
  material/night-sky/2026-08-24-continuing/fetch-and-check.txt). No committed
  value changed; the field is new.
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

SOURCES = {
    # the newest committed join: every recorded wake x the sky's record
    "join": "material/night-sky/2026-09-03-continuing/join.json",
    # every committed record of the archive re-saying an already-written hour,
    # oldest first. first_read gives the date the practice first committed each
    # hour's telling: a plain string, or a threshold dict
    # {"threshold": MESS_DATUM, "before": date, "at_or_after": date}.
    "rewrites": [
        {
            "path": "material/night-sky/2026-08-24-continuing/indicator-rewrite-2026-08-20.txt",
            "first_read": "2026-08-22",
            "retold_read": "2026-08-24",
        },
        {
            # 2026-08-21 rows first committed in the prospect slice (read
            # 2026-08-22); the 2026-08-22 00:00 row in the eighth-date slice
            # (read 2026-08-24)
            "path": "material/night-sky/2026-08-25-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026082200", "before": "2026-08-22",
                           "at_or_after": "2026-08-24"},
            "retold_read": "2026-08-25",
        },
        {
            # 2026-08-22 rows first committed in the eighth-date slice (read
            # 2026-08-24); 2026-08-23 rows in the ninth-date slice (read
            # 2026-08-25)
            "path": "material/night-sky/2026-08-28-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026082300", "before": "2026-08-24",
                           "at_or_after": "2026-08-25"},
            "retold_read": "2026-08-28",
        },
        {
            # all 24 rows (2026-08-25 01:00 .. 2026-08-26 00:00) first
            # committed in the tenth-to-twelfth-date slices (read 2026-08-28)
            "path": "material/night-sky/2026-08-29-continuing/indicator-rewrite-frontier.txt",
            "first_read": "2026-08-28",
            "retold_read": "2026-08-29",
        },
        {
            # 2026-08-26 01:00..23:00 first committed in the twelfth-date slice
            # (read 2026-08-28); the 2026-08-27 00:00 row in the thirteenth-date
            # slice (read 2026-08-29)
            "path": "material/night-sky/2026-08-30-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026082700", "before": "2026-08-28",
                           "at_or_after": "2026-08-29"},
            "retold_read": "2026-08-30",
        },
        {
            # 2026-08-27 01:00..23:00 first committed in the thirteenth-date
            # slice (read 2026-08-29); the 2026-08-28 00:00 row in the
            # fourteenth-date slice (read 2026-08-30)
            "path": "material/night-sky/2026-08-31-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026082800", "before": "2026-08-29",
                           "at_or_after": "2026-08-30"},
            "retold_read": "2026-08-31",
        },
        {
            # 2026-08-28 01:00..23:00 first committed in the fourteenth-date
            # slice (read 2026-08-30); the 2026-08-29 00:00 row in the
            # fifteenth-date slice (read 2026-08-31)
            "path": "material/night-sky/2026-09-01-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026082900", "before": "2026-08-30",
                           "at_or_after": "2026-08-31"},
            "retold_read": "2026-09-01",
        },
        {
            # 2026-08-29 01:00..23:00 first committed in the fifteenth-date
            # slice (read 2026-08-31); the 2026-08-30 00:00 row in the
            # sixteenth-date slice (read 2026-09-01)
            "path": "material/night-sky/2026-09-02-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026083000", "before": "2026-08-31",
                           "at_or_after": "2026-09-01"},
            "retold_read": "2026-09-02",
        },
        {
            # 2026-08-30 01:00..23:00 first committed in the sixteenth-date
            # slice (read 2026-09-01); the 2026-08-31 00:00 row in the
            # seventeenth-date slice (read 2026-09-02)
            "path": "material/night-sky/2026-09-03-continuing/indicator-rewrite-frontier.txt",
            "first_read": {"threshold": "2026083100", "before": "2026-09-01",
                           "at_or_after": "2026-09-02"},
            "retold_read": "2026-09-03",
        },
    ],
    # the practice's dated readings of the archive, with where the boundary
    # between instrument-told and person-told rows stood in each (the frontier;
    # material/night-sky/2026-08-28-continuing/README.md, finding 2)
    "readings": [
        {"read": "2026-08-22", "generation": "2026-08-22 08:18",
         "person_rows_begin": "2026-08-20 01:00 UTC",
         "window_end": "2026-08-21 23:00 UTC",
         "evidence": "material/night-sky/2026-08-22-prospect/"},
        {"read": "2026-08-24", "generation": "2026-08-23 08:18",
         "person_rows_begin": "2026-08-21 01:00 UTC",
         "window_end": "2026-08-22 23:00 UTC",
         "evidence": "material/night-sky/2026-08-24-continuing/"},
        {"read": "2026-08-25", "generation": "2026-08-24 08:18",
         "person_rows_begin": "2026-08-22 01:00 UTC",
         "window_end": "2026-08-23 23:00 UTC",
         "evidence": "material/night-sky/2026-08-25-continuing/"},
        {"read": "2026-08-28", "generation": "2026-08-27 08:18",
         "person_rows_begin": "2026-08-25 01:00 UTC",
         "window_end": "2026-08-26 23:00 UTC",
         "evidence": "material/night-sky/2026-08-28-continuing/"},
        {"read": "2026-08-29", "generation": "2026-08-28 08:18",
         "person_rows_begin": "2026-08-26 01:00 UTC",
         "window_end": "2026-08-27 23:00 UTC",
         "evidence": "material/night-sky/2026-08-29-continuing/"},
        {"read": "2026-08-30", "generation": "2026-08-29 08:17",
         "person_rows_begin": "2026-08-27 01:00 UTC",
         "window_end": "2026-08-28 23:00 UTC",
         "evidence": "material/night-sky/2026-08-30-continuing/"},
        {"read": "2026-08-31", "generation": "2026-08-30 08:17",
         "person_rows_begin": "2026-08-28 01:00 UTC",
         "window_end": "2026-08-29 23:00 UTC",
         "evidence": "material/night-sky/2026-08-31-continuing/"},
        {"read": "2026-09-01", "generation": "2026-08-31 08:18",
         "person_rows_begin": "2026-08-29 01:00 UTC",
         "window_end": "2026-08-30 23:00 UTC",
         "evidence": "material/night-sky/2026-09-01-continuing/"},
        {"read": "2026-09-02", "generation": "2026-09-01 08:18",
         "person_rows_begin": "2026-08-30 01:00 UTC",
         "window_end": "2026-08-31 23:00 UTC",
         "evidence": "material/night-sky/2026-09-02-continuing/"},
        {"read": "2026-09-03", "generation": "2026-09-02 08:22",
         "person_rows_begin": "2026-08-31 01:00 UTC",
         "window_end": "2026-09-01 23:00 UTC",
         "evidence": "material/night-sky/2026-09-03-continuing/"},
    ],
}


def resolve_first_read(fr, key):
    if isinstance(fr, str):
        return fr
    # threshold dict: rows before the threshold MESS_DATUM carry one date,
    # rows at or after it carry another
    return fr["before"] if key < fr["threshold"] else fr["at_or_after"]


# hours the archive has re-said, from the committed rewrite records:
# MESS_DATUM -> {first, current, first_read, retold_read}. Records are applied
# oldest first; a later record overwrites an earlier telling of the same hour,
# so 'current' always holds the newest committed telling.
retold = {}
row_re = re.compile(r"^(\d{10})\s")
for rw in SOURCES["rewrites"]:
    for line in open(os.path.join(ROOT, rw["path"])):
        m = row_re.match(line)
        if not m:
            continue
        key = m.group(1)
        # the file forms carry the two indicator states as ';P;' -> ';I;' etc.
        states = re.findall(r";\s*(P|I|-999)\s*;", line)
        if len(states) >= 2:
            # records are applied oldest-reading first. A row re-said in more
            # than one generation keeps its first telling and the FIRST reading
            # at which the practice observed the change (prev's retold_read);
            # 'current' advances to the newest committed telling.
            prev = retold.get(key)
            first = prev["first"] if prev else states[0]
            first_read = prev["first_read"] if prev else resolve_first_read(rw["first_read"], key)
            retold_read = prev["retold_read"] if prev else rw["retold_read"]
            retold[key] = {
                "first": first, "current": states[-1],
                "first_read": first_read, "retold_read": retold_read,
                "evidence": prev["evidence"] if prev else rw["path"],
            }

join = json.load(open(os.path.join(ROOT, SOURCES["join"])))
wakes = []
for r in join:
    key = r["wake_utc"][:13].replace("-", "").replace("T", "")
    entry = {
        "session": r["session"],
        "record": r["record"],
        "wake_utc": r["wake_utc"],
        "berlin_local": r["berlin_local_cest"],
        "sky_eighths": r["cloud_cover_eighths_wake_hour"],
        "indicator": r["measurement_indicator"],
    }
    if key in retold:
        entry["retold"] = retold[key]
    wakes.append(entry)

ledger = {
    "work": "two-nights-deep",
    "note": ("The work's ledger, derived from the committed record alone by "
             "build.py (FORM.md §3). One entry per recorded wake of the "
             "practice's life; sky values as the archive first told them in "
             "the practice's committed slices; 'retold' where the archive's "
             "later generations re-said the hour. sky_eighths null = the "
             "world had not written that night as of the build."),
    "attribution": ("Source: Deutscher Wetterdienst (DWD), Climate Data "
                    "Center, hourly cloud cover (V_N, eighths), station "
                    "00433 Berlin-Tempelhof, CC BY 4.0"),
    "sources": SOURCES,
    "wakes": wakes,
}
json.dump(ledger, open(os.path.join(HERE, "nights.json"), "w"), indent=1)
unwritten = [w for w in wakes if w["sky_eighths"] is None]
print(f"{len(wakes)} wakes; {len(unwritten)} unwritten "
      f"({[w['session'] for w in unwritten]}); {len(retold)} hours retold, "
      f"{sum(1 for w in wakes if 'retold' in w)} of them at a wake hour")
